apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  BINANCE_TESTNET_API_KEY: {{ .Values.secrets.binanceApiKey | quote }}
  BINANCE_TESTNET_SECRET_KEY: {{ .Values.secrets.binanceSecretKey | quote }}
  GROQ_API_KEY: {{ .Values.secrets.groqApiKey | quote }}