global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'market-data-collector'
    static_configs:
      - targets: ['172.17.0.1:8001']
    metrics_path: '/metrics'

  - job_name: 'ml-decision-engine'
    static_configs:
      - targets: ['172.17.0.1:8002']
    metrics_path: '/metrics'

  - job_name: 'order-executor'
    static_configs:
      - targets: ['172.17.0.1:8004']
    metrics_path: '/metrics'