# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ml_engine.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'ml_engine.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fml_engine.proto\x12\tml_engine\"\x9d\x01\n\x0ePredictRequest\x12\x0e\n\x06symbol\x18\x01 \x01(\t\x12\x39\n\x08\x66\x65\x61tures\x18\x02 \x03(\x0b\x32\'.ml_engine.PredictRequest.FeaturesEntry\x12\x0f\n\x07publish\x18\x03 \x01(\x08\x1a/\n\rFeaturesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x01:\x02\x38\x01\"\xd0\x01\n\x0fPredictResponse\x12\x0e\n\x06symbol\x18\x01 \x01(\t\x12\x0e\n\x06signal\x18\x02 \x01(\t\x12\x12\n\nconfidence\x18\x03 \x01(\x01\x12\r\n\x05model\x18\x04 \x01(\t\x12\x44\n\rprobabilities\x18\x05 \x03(\x0b\x32-.ml_engine.PredictResponse.ProbabilitiesEntry\x1a\x34\n\x12ProbabilitiesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x01:\x02\x38\x01\"\x0f\n\rHealthRequest\"1\n\x0eHealthResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07service\x18\x02 \x01(\t\"\x10\n\x0eSymbolsRequest\"\"\n\x0fSymbolsResponse\x12\x0f\n\x07symbols\x18\x01 \x03(\t2\xda\x01\n\x0fMLEngineService\x12@\n\x07Predict\x12\x19.ml_engine.PredictRequest\x1a\x1a.ml_engine.PredictResponse\x12@\n\tGetHealth\x12\x18.ml_engine.HealthRequest\x1a\x19.ml_engine.HealthResponse\x12\x43\n\nGetSymbols\x12\x19.ml_engine.SymbolsRequest\x1a\x1a.ml_engine.SymbolsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ml_engine_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PREDICTREQUEST_FEATURESENTRY']._loaded_options = None
  _globals['_PREDICTREQUEST_FEATURESENTRY']._serialized_options = b'8\001'
  _globals['_PREDICTRESPONSE_PROBABILITIESENTRY']._loaded_options = None
  _globals['_PREDICTRESPONSE_PROBABILITIESENTRY']._serialized_options = b'8\001'
  _globals['_PREDICTREQUEST']._serialized_start=31
  _globals['_PREDICTREQUEST']._serialized_end=188
  _globals['_PREDICTREQUEST_FEATURESENTRY']._serialized_start=141
  _globals['_PREDICTREQUEST_FEATURESENTRY']._serialized_end=188
  _globals['_PREDICTRESPONSE']._serialized_start=191
  _globals['_PREDICTRESPONSE']._serialized_end=399
  _globals['_PREDICTRESPONSE_PROBABILITIESENTRY']._serialized_start=347
  _globals['_PREDICTRESPONSE_PROBABILITIESENTRY']._serialized_end=399
  _globals['_HEALTHREQUEST']._serialized_start=401
  _globals['_HEALTHREQUEST']._serialized_end=416
  _globals['_HEALTHRESPONSE']._serialized_start=418
  _globals['_HEALTHRESPONSE']._serialized_end=467
  _globals['_SYMBOLSREQUEST']._serialized_start=469
  _globals['_SYMBOLSREQUEST']._serialized_end=485
  _globals['_SYMBOLSRESPONSE']._serialized_start=487
  _globals['_SYMBOLSRESPONSE']._serialized_end=521
  _globals['_MLENGINESERVICE']._serialized_start=524
  _globals['_MLENGINESERVICE']._serialized_end=742
# @@protoc_insertion_point(module_scope)
