# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: order_executor.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'order_executor.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14order_executor.proto\x12\x0eorder_executor\" \n\x0e\x45xecuteRequest\x12\x0e\n\x06symbol\x18\x01 \x01(\t\"t\n\x0f\x45xecuteResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0e\n\x06signal\x18\x02 \x01(\t\x12\x12\n\nconfidence\x18\x03 \x01(\x01\x12\r\n\x05model\x18\x04 \x01(\t\x12\r\n\x05price\x18\x05 \x01(\x01\x12\x0f\n\x07message\x18\x06 \x01(\t\"\x10\n\x0e\x42\x61lanceRequest\"I\n\x0f\x42\x61lanceResponse\x12\x0e\n\x06source\x18\x01 \x01(\t\x12\x0c\n\x04usdt\x18\x02 \x01(\x01\x12\x0b\n\x03\x62tc\x18\x03 \x01(\x01\x12\x0b\n\x03\x65th\x18\x04 \x01(\x01\"\x1f\n\rSignalRequest\x12\x0e\n\x06symbol\x18\x01 \x01(\t\"R\n\x0eSignalResponse\x12\x0e\n\x06signal\x18\x01 \x01(\t\x12\x12\n\nconfidence\x18\x02 \x01(\x01\x12\r\n\x05model\x18\x03 \x01(\t\x12\r\n\x05price\x18\x04 \x01(\x01\".\n\rTradesRequest\x12\x0e\n\x06symbol\x18\x01 \x01(\t\x12\r\n\x05limit\x18\x02 \x01(\x05\"\x81\x01\n\x05Trade\x12\x0e\n\x06symbol\x18\x01 \x01(\t\x12\x0e\n\x06signal\x18\x02 \x01(\t\x12\r\n\x05price\x18\x03 \x01(\x01\x12\x10\n\x08quantity\x18\x04 \x01(\x01\x12\x12\n\nconfidence\x18\x05 \x01(\x01\x12\x0e\n\x06status\x18\x06 \x01(\t\x12\x13\n\x0b\x65xecuted_at\x18\x07 \x01(\t\"7\n\x0eTradesResponse\x12%\n\x06trades\x18\x01 \x03(\x0b\x32\x15.order_executor.Trade\"\x0f\n\rHealthRequest\"1\n\x0eHealthResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07service\x18\x02 \x01(\t2\x95\x03\n\x14OrderExecutorService\x12J\n\x07\x45xecute\x12\x1e.order_executor.ExecuteRequest\x1a\x1f.order_executor.ExecuteResponse\x12M\n\nGetBalance\x12\x1e.order_executor.BalanceRequest\x1a\x1f.order_executor.BalanceResponse\x12J\n\tGetSignal\x12\x1d.order_executor.SignalRequest\x1a\x1e.order_executor.SignalResponse\x12J\n\tGetTrades\x12\x1d.order_executor.TradesRequest\x1a\x1e.order_executor.TradesResponse\x12J\n\tGetHealth\x12\x1d.order_executor.HealthRequest\x1a\x1e.order_executor.HealthResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'order_executor_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EXECUTEREQUEST']._serialized_start=40
  _globals['_EXECUTEREQUEST']._serialized_end=72
  _globals['_EXECUTERESPONSE']._serialized_start=74
  _globals['_EXECUTERESPONSE']._serialized_end=190
  _globals['_BALANCEREQUEST']._serialized_start=192
  _globals['_BALANCEREQUEST']._serialized_end=208
  _globals['_BALANCERESPONSE']._serialized_start=210
  _globals['_BALANCERESPONSE']._serialized_end=283
  _globals['_SIGNALREQUEST']._serialized_start=285
  _globals['_SIGNALREQUEST']._serialized_end=316
  _globals['_SIGNALRESPONSE']._serialized_start=318
  _globals['_SIGNALRESPONSE']._serialized_end=400
  _globals['_TRADESREQUEST']._serialized_start=402
  _globals['_TRADESREQUEST']._serialized_end=448
  _globals['_TRADE']._serialized_start=451
  _globals['_TRADE']._serialized_end=580
  _globals['_TRADESRESPONSE']._serialized_start=582
  _globals['_TRADESRESPONSE']._serialized_end=637
  _globals['_HEALTHREQUEST']._serialized_start=639
  _globals['_HEALTHREQUEST']._serialized_end=654
  _globals['_HEALTHRESPONSE']._serialized_start=656
  _globals['_HEALTHRESPONSE']._serialized_end=705
  _globals['_ORDEREXECUTORSERVICE']._serialized_start=708
  _globals['_ORDEREXECUTORSERVICE']._serialized_end=1113
# @@protoc_insertion_point(module_scope)
