# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sentiment.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'sentiment.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fsentiment.proto\x12\tsentiment\"\x1f\n\x0eSummaryRequest\x12\r\n\x05\x61sset\x18\x01 \x01(\t\"\x8c\x01\n\x0fSummaryResponse\x12\r\n\x05\x61sset\x18\x01 \x01(\t\x12\x13\n\x0btotal_posts\x18\x02 \x01(\x05\x12\x10\n\x08positive\x18\x03 \x01(\x05\x12\x10\n\x08negative\x18\x04 \x01(\x05\x12\x0f\n\x07neutral\x18\x05 \x01(\x05\x12\x11\n\tavg_score\x18\x06 \x01(\x01\x12\r\n\x05label\x18\x07 \x01(\t\"\x0f\n\rHealthRequest\"1\n\x0eHealthResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07service\x18\x02 \x01(\t2\x99\x01\n\x10SentimentService\x12\x43\n\nGetSummary\x12\x19.sentiment.SummaryRequest\x1a\x1a.sentiment.SummaryResponse\x12@\n\tGetHealth\x12\x18.sentiment.HealthRequest\x1a\x19.sentiment.HealthResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sentiment_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SUMMARYREQUEST']._serialized_start=30
  _globals['_SUMMARYREQUEST']._serialized_end=61
  _globals['_SUMMARYRESPONSE']._serialized_start=64
  _globals['_SUMMARYRESPONSE']._serialized_end=204
  _globals['_HEALTHREQUEST']._serialized_start=206
  _globals['_HEALTHREQUEST']._serialized_end=221
  _globals['_HEALTHRESPONSE']._serialized_start=223
  _globals['_HEALTHRESPONSE']._serialized_end=272
  _globals['_SENTIMENTSERVICE']._serialized_start=275
  _globals['_SENTIMENTSERVICE']._serialized_end=428
# @@protoc_insertion_point(module_scope)
