# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: chatbot.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'chatbot.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rchatbot.proto\x12\x07\x63hatbot\"\x1e\n\nAskRequest\x12\x10\n\x08question\x18\x01 \x01(\t\".\n\x0b\x41skResponse\x12\x0e\n\x06\x61nswer\x18\x01 \x01(\t\x12\x0f\n\x07sources\x18\x02 \x03(\t\"\x0f\n\rHealthRequest\"1\n\x0eHealthResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07service\x18\x02 \x01(\t2\x80\x01\n\x0e\x43hatbotService\x12\x30\n\x03\x41sk\x12\x13.chatbot.AskRequest\x1a\x14.chatbot.AskResponse\x12<\n\tGetHealth\x12\x16.chatbot.HealthRequest\x1a\x17.chatbot.HealthResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chatbot_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ASKREQUEST']._serialized_start=26
  _globals['_ASKREQUEST']._serialized_end=56
  _globals['_ASKRESPONSE']._serialized_start=58
  _globals['_ASKRESPONSE']._serialized_end=104
  _globals['_HEALTHREQUEST']._serialized_start=106
  _globals['_HEALTHREQUEST']._serialized_end=121
  _globals['_HEALTHRESPONSE']._serialized_start=123
  _globals['_HEALTHRESPONSE']._serialized_end=172
  _globals['_CHATBOTSERVICE']._serialized_start=175
  _globals['_CHATBOTSERVICE']._serialized_end=303
# @@protoc_insertion_point(module_scope)
