# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import market_data_pb2 as market__data__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in market_data_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MarketDataServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetPrice = channel.unary_unary(
                '/market_data.MarketDataService/GetPrice',
                request_serializer=market__data__pb2.PriceRequest.SerializeToString,
                response_deserializer=market__data__pb2.PriceResponse.FromString,
                _registered_method=True)
        self.GetOHLCV = channel.unary_unary(
                '/market_data.MarketDataService/GetOHLCV',
                request_serializer=market__data__pb2.OHLCVRequest.SerializeToString,
                response_deserializer=market__data__pb2.OHLCVResponse.FromString,
                _registered_method=True)
        self.GetHealth = channel.unary_unary(
                '/market_data.MarketDataService/GetHealth',
                request_serializer=market__data__pb2.HealthRequest.SerializeToString,
                response_deserializer=market__data__pb2.HealthResponse.FromString,
                _registered_method=True)
        self.StreamCandles = channel.unary_stream(
                '/market_data.MarketDataService/StreamCandles',
                request_serializer=market__data__pb2.StreamRequest.SerializeToString,
                response_deserializer=market__data__pb2.Candle.FromString,
                _registered_method=True)


class MarketDataServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetPrice(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOHLCV(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetHealth(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamCandles(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MarketDataServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetPrice': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPrice,
                    request_deserializer=market__data__pb2.PriceRequest.FromString,
                    response_serializer=market__data__pb2.PriceResponse.SerializeToString,
            ),
            'GetOHLCV': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOHLCV,
                    request_deserializer=market__data__pb2.OHLCVRequest.FromString,
                    response_serializer=market__data__pb2.OHLCVResponse.SerializeToString,
            ),
            'GetHealth': grpc.unary_unary_rpc_method_handler(
                    servicer.GetHealth,
                    request_deserializer=market__data__pb2.HealthRequest.FromString,
                    response_serializer=market__data__pb2.HealthResponse.SerializeToString,
            ),
            'StreamCandles': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamCandles,
                    request_deserializer=market__data__pb2.StreamRequest.FromString,
                    response_serializer=market__data__pb2.Candle.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'market_data.MarketDataService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('market_data.MarketDataService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MarketDataService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetPrice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/market_data.MarketDataService/GetPrice',
            market__data__pb2.PriceRequest.SerializeToString,
            market__data__pb2.PriceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetOHLCV(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/market_data.MarketDataService/GetOHLCV',
            market__data__pb2.OHLCVRequest.SerializeToString,
            market__data__pb2.OHLCVResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetHealth(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/market_data.MarketDataService/GetHealth',
            market__data__pb2.HealthRequest.SerializeToString,
            market__data__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamCandles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/market_data.MarketDataService/StreamCandles',
            market__data__pb2.StreamRequest.SerializeToString,
            market__data__pb2.Candle.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
