# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: market_data.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'market_data.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11market_data.proto\x12\x0bmarket_data\"\x1e\n\x0cPriceRequest\x12\x0e\n\x06symbol\x18\x01 \x01(\t\"l\n\rPriceResponse\x12\x0e\n\x06symbol\x18\x01 \x01(\t\x12\r\n\x05price\x18\x02 \x01(\x01\x12\x0c\n\x04high\x18\x03 \x01(\x01\x12\x0b\n\x03low\x18\x04 \x01(\x01\x12\x0e\n\x06volume\x18\x05 \x01(\x01\x12\x11\n\ttimestamp\x18\x06 \x01(\t\"-\n\x0cOHLCVRequest\x12\x0e\n\x06symbol\x18\x01 \x01(\t\x12\r\n\x05limit\x18\x02 \x01(\x05\"\x8c\x01\n\x06\x43\x61ndle\x12\x11\n\ttimestamp\x18\x01 \x01(\t\x12\x0c\n\x04open\x18\x02 \x01(\x01\x12\x0c\n\x04high\x18\x03 \x01(\x01\x12\x0b\n\x03low\x18\x04 \x01(\x01\x12\r\n\x05\x63lose\x18\x05 \x01(\x01\x12\x0e\n\x06volume\x18\x06 \x01(\x01\x12\x0b\n\x03rsi\x18\x07 \x01(\x01\x12\x0c\n\x04ma20\x18\x08 \x01(\x01\x12\x0c\n\x04ma50\x18\t \x01(\x01\"5\n\rOHLCVResponse\x12$\n\x07\x63\x61ndles\x18\x01 \x03(\x0b\x32\x13.market_data.Candle\"\x0f\n\rHealthRequest\"1\n\x0eHealthResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07service\x18\x02 \x01(\t2\xdf\x01\n\x11MarketDataService\x12\x41\n\x08GetPrice\x12\x19.market_data.PriceRequest\x1a\x1a.market_data.PriceResponse\x12\x41\n\x08GetOHLCV\x12\x19.market_data.OHLCVRequest\x1a\x1a.market_data.OHLCVResponse\x12\x44\n\tGetHealth\x12\x1a.market_data.HealthRequest\x1a\x1b.market_data.HealthResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'market_data_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PRICEREQUEST']._serialized_start=34
  _globals['_PRICEREQUEST']._serialized_end=64
  _globals['_PRICERESPONSE']._serialized_start=66
  _globals['_PRICERESPONSE']._serialized_end=174
  _globals['_OHLCVREQUEST']._serialized_start=176
  _globals['_OHLCVREQUEST']._serialized_end=221
  _globals['_CANDLE']._serialized_start=224
  _globals['_CANDLE']._serialized_end=364
  _globals['_OHLCVRESPONSE']._serialized_start=366
  _globals['_OHLCVRESPONSE']._serialized_end=419
  _globals['_HEALTHREQUEST']._serialized_start=421
  _globals['_HEALTHREQUEST']._serialized_end=436
  _globals['_HEALTHRESPONSE']._serialized_start=438
  _globals['_HEALTHRESPONSE']._serialized_end=487
  _globals['_MARKETDATASERVICE']._serialized_start=490
  _globals['_MARKETDATASERVICE']._serialized_end=713
# @@protoc_insertion_point(module_scope)
