# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from app import ml_engine_pb2 as ml__engine__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in ml_engine_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MLEngineServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Predict = channel.unary_unary(
                '/ml_engine.MLEngineService/Predict',
                request_serializer=ml__engine__pb2.PredictRequest.SerializeToString,
                response_deserializer=ml__engine__pb2.PredictResponse.FromString,
                _registered_method=True)
        self.GetHealth = channel.unary_unary(
                '/ml_engine.MLEngineService/GetHealth',
                request_serializer=ml__engine__pb2.HealthRequest.SerializeToString,
                response_deserializer=ml__engine__pb2.HealthResponse.FromString,
                _registered_method=True)
        self.GetSymbols = channel.unary_unary(
                '/ml_engine.MLEngineService/GetSymbols',
                request_serializer=ml__engine__pb2.SymbolsRequest.SerializeToString,
                response_deserializer=ml__engine__pb2.SymbolsResponse.FromString,
                _registered_method=True)


class MLEngineServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Predict(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetHealth(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSymbols(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MLEngineServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Predict': grpc.unary_unary_rpc_method_handler(
                    servicer.Predict,
                    request_deserializer=ml__engine__pb2.PredictRequest.FromString,
                    response_serializer=ml__engine__pb2.PredictResponse.SerializeToString,
            ),
            'GetHealth': grpc.unary_unary_rpc_method_handler(
                    servicer.GetHealth,
                    request_deserializer=ml__engine__pb2.HealthRequest.FromString,
                    response_serializer=ml__engine__pb2.HealthResponse.SerializeToString,
            ),
            'GetSymbols': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSymbols,
                    request_deserializer=ml__engine__pb2.SymbolsRequest.FromString,
                    response_serializer=ml__engine__pb2.SymbolsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ml_engine.MLEngineService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ml_engine.MLEngineService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MLEngineService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Predict(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ml_engine.MLEngineService/Predict',
            ml__engine__pb2.PredictRequest.SerializeToString,
            ml__engine__pb2.PredictResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetHealth(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ml_engine.MLEngineService/GetHealth',
            ml__engine__pb2.HealthRequest.SerializeToString,
            ml__engine__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSymbols(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ml_engine.MLEngineService/GetSymbols',
            ml__engine__pb2.SymbolsRequest.SerializeToString,
            ml__engine__pb2.SymbolsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
